[[unit]]
id = 1
name = "test_2"
sprite_id = 1
positions = [[11, 13], [3, 13], [5, 5], [13, 5], [13, 9]]
patrols = [[], [], [], [[15, 8], [14, 2]], [[11, 8], [13, 5], [16, 7]]]

[unit.stats]
health = 1
speed = 0.1
